### ISSUE TITLE
Error running python command

### ISSUE THREAD

**Issue by kpotschi** [mightbesimon/vscode-emoji-icons#20]
Following the `contributing.md` and running `python3 -m translate`, i am greeted with the following error: 
`FileNotFoundError: [Errno 2] No such file or directory: 'file-icons/emoji-icon-theme.json'`

Would love to get this working and contribute!

**Comment by mightbesimon** [comment]
Thank you for the report, @kpotschi 🙂
This issue has been resolved in #23 by @itsamedood (https://github.com/mightbesimon/vscode-emoji-icons/pull/23). Please let me know if there is any further issues. For the mean time, I will mark it as resolved!
