### ISSUE TITLE
Missing Icon for Source Control (Possible 🌿, ⚓, ☁️, 🌲)

### ISSUE THREAD

**Issue by ghost** [mightbesimon/vscode-emoji-icons#24]
**Problem**

This icon pack currently doesn't have an icon for the Source Control product icon, which is one of the essential parts of VSCode.

![image](https://github.com/mightbesimon/vscode-emoji-icons/assets/144612896/0297bfc2-bfd9-42ed-b217-13c57412bc02)

**Solution**

Add an icon for Source Control. Possible icons would be:

- 🌿 (branch)
- ⚓ (anchor)
- ☁️ (cloud)
- 🌲 (tree)

**Comment by ghost** [comment]
NVM, found out this is already available, you just have to use the Fun version.

**Comment by mightbesimon** [comment]
You're correct! It's in the 'fun' version
The 🌿 (branch) emoji doesn't represents source control intuitively enough, so I did not include it in the 'serious' version. I really like your idea of the ⚓️ (anchor) emoji, but I can't elaborate exactly why. Perhaps you can help me? @aarvinr
