### ISSUE TITLE
Can not use in newest version VSCode

### ISSUE THREAD

**Issue by Wloner0809** [mightbesimon/vscode-emoji-icons#26]
Thanks for the great extension! 

I have used it for about one year, but this morning when I update VSCode, it doesn't work.
![image](https://github.com/user-attachments/assets/4be44a13-2d76-4c06-8fee-c0b466460e7b)

**Comment by GuoChen-thlg** [comment]
+1

**Comment by kkqin** [comment]
help

**Comment by eraimundez** [comment]
same here!

**Comment by Joinyy** [comment]
I think this could be the root-cause:

```
2024-12-12 13:12:15.806 [error] Problems processing product icons definitions in file:///c%3A/Users/xxx/.vscode/extensions/mightbesimon.emoji-icons-1.6.1/product-icons/emoji-product-icon-theme.json:
Skipping icon definition 'files'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
Skipping icon definition 'search'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
Skipping icon definition 'debug-alt'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
Skipping icon definition 'extensions'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
...
```

There was no change mentioned in the VSCode release notes that there will be a change regarding icon definitions. Maybe this should be raised as an issue in the official vs-code repo?

**Comment by Wloner0809** [comment]
> I think this could be the root-cause:
> 
> ```
> 2024-12-12 13:12:15.806 [error] Problems processing product icons definitions in file:///c%3A/Users/xxx/.vscode/extensions/mightbesimon.emoji-icons-1.6.1/product-icons/emoji-product-icon-theme.json:
> Skipping icon definition 'files'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
> Skipping icon definition 'search'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
> Skipping icon definition 'debug-alt'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
> Skipping icon definition 'extensions'. Unknown fontCharacter. Must use a sing; character or a \ followed by a Unicode code points in hexadecimal.
> ...
> ```
> 
> There was no change mentioned in the VSCode release notes that there will be a change regarding icon definitions. Maybe this should be raised as an issue in the official vs-code repo?

Probably you are right! I will close this issue and anyone interested in this issue can go to [235942#issue-2735807589](https://github.com/microsoft/vscode/issues/235942#issue-2735807589)

**Comment by mightbesimon** [comment]
Thank you @Joinyy for raising this issue in the official vscode repo (https://github.com/microsoft/vscode/issues/235942). According to the vscode changelogs for v1.96.1, they have resolved the issue regarding this behaviour. Presumably now, updating to ≥v1.96.1 would resolve the problem. Please feel free to reopen the issue if that does not work.
