### ISSUE TITLE
主题不生效了

### ISSUE THREAD

**Issue by Fa-ce** [mightbesimon/vscode-emoji-icons#27]
VS code 更新 1.96 版本之后，设置侧边栏主题不生效了
![QQ截图20241214105200](https://github.com/user-attachments/assets/a00f797a-3ab1-44a2-8de5-e4d6b6ea33f8)

**Comment by jabclqo** [comment]
Both side panel and files doesn't work. 
![image](https://github.com/user-attachments/assets/6e875a10-823e-4daf-968c-0ed617799925)
The env now looks too clean for my liking :smile:

**Comment by Fa-ce** [comment]
It may be the problem of VS Code

**Comment by Fa-ce** [comment]
It may be the problem of VS Code

**Comment by Fa-ce** [comment]
the last version has solved this problem

**Comment by mightbesimon** [comment]
Duplicate of #26
